In [1]:
import requests
from datetime import datetime
from pathlib import Path
import pandas as pd


BASE_FILE_DIR = Path('/tmp')
file_path_crib = '{category}/{year}-{month:02d}/{category}-{day:02d}-{month:02d}-{year}.csv'

In [2]:
categories=[
    {
        'name': 'museo',
        'url': 'https://datos.cultura.gob.ar/dataset/37305de4-3cce-4d4b-9d9a-fec3ca61d09f/resource/4207def0-2ff7-41d5-9095-d42ae8207a5d/download/museo.csv'
    },
    {
        'name': 'cines',
        'url': 'https://datos.cultura.gob.ar/dataset/37305de4-3cce-4d4b-9d9a-fec3ca61d09f/resource/392ce1a8-ef11-4776-b280-6f1c7fae16ae/download/cine.csv'
    },
    {
        'name': 'bibliotecas_populares',
        'url': 'https://datos.cultura.gob.ar/dataset/37305de4-3cce-4d4b-9d9a-fec3ca61d09f/resource/01c6c048-dbeb-44e0-8efa-6944f73715d7/download/biblioteca_popular.csv'
    },
]

MUSEOS

In [3]:
category_dict = categories[0]
r = requests.get(category_dict['url'])
r.encoding = 'utf-8'

In [4]:
now = datetime.now()

file_path = file_path_crib.format(category=category_dict['name'], year=now.year, month=now.month,day=now.day)

m_path = BASE_FILE_DIR / file_path
m_path.parent.mkdir(parents=True, exist_ok=True)

## Save file
with open(m_path, 'w') as f_out:
    f_out.write(r.text)

Transform

In [7]:
df = pd.read_csv(m_path,encoding='latin-1')

In [8]:
df.head()

,Cod_Loc,IdProvincia,IdDepartamento,Observaciones,categoria,subcategoria,provincia,localidad,nombre,direccion,...,Mail,Web,Latitud,Longitud,TipoLatitudLongitud,Info_adicional,fuente,jurisdiccion,año_inauguracion,actualizacion
0,6588100,6,6588,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,9 de Julio,Archivo Y Museo Histórico Gral. Julio De Vedia,Libertad 1191,...,archivoymuseo@yahoo.com.ar,www.portaldel9.com.ar,-35.441762,-60.887598,Localización precisa,NaN,DNPyM,Municipal,1920.0,2017
1,6077010,6,6077,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Arrecifes,Museo Y Archivo Histórico De Arrecifes,Gerardo Risso y España,...,museoarrecifes@hotmail.com,NaN,-34.066970,-60.102555,Localización precisa,NaN,DNPyM,Municipal,1972.0,2017
2,6035010,6,6035,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Avellaneda,Museo Histórico-Sacro Hno. Rogelio Scortegagna,Calle 11 (Av. San Martín) Nº 830,...,NaN,NaN,-29.118024,-59.654543,Localización precisa,NaN,DNPyM,Municipal,NaN,2017
3,6035010,6,6035,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Avellaneda,Museo Municipal De Artes Plásticas De Avellaneda,"Sarmiento 101, 1 º Piso",...,NaN,NaN,-34.662110,-58.363270,Localización precisa,NaN,DNPyM,Municipal,1956.0,2017
4,6049020,6,6049,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Azul,Museo Etnográfico Y Archivo Histórico Enrique ...,Bartolomé J. Ronco 654,...,museoazul@yahoo.com,NaN,-36.781824,-59.858636,Localización precisa,NaN,DNPyM,Privada,1949.0,2017

In [9]:
df.columns

Index(['Cod_Loc', 'IdProvincia', 'IdDepartamento', 'Observaciones',
       'categoria', 'subcategoria', 'provincia', 'localidad', 'nombre',
       'direccion', 'piso', 'CP', 'cod_area', 'telefono', 'Mail', 'Web',
       'Latitud', 'Longitud', 'TipoLatitudLongitud', 'Info_adicional',
       'fuente', 'jurisdiccion', 'año_inauguracion', 'actualizacion'],
      dtype='object')

In [12]:
renamed_cols = {
    'Cod_Loc': 'cod_localidad',
    'IdProvincia': 'id_provincia',
    'IdDepartamento': 'id_departamento',
    'direccion': 'domicilio',
    'CP': 'codigo postal',
    'telefono': 'número de teléfono',
    'Mail': 'mail',
    'Web': 'web',
    
}

df = df.rename(columns = renamed_cols)

colum_list = [
    'cod_localidad',
    'id_provincia',
    'id_departamento',
    'categoria',
    'provincia',
    'localidad',
    'nombre',
    'domicilio',
    'codigo postal',
    'número de teléfono',
    'mail',
    'web',
]
df_m= df[colum_list]

Cines

In [15]:
now = datetime.now()

category_dict = categories[1]
r = requests.get(category_dict['url'])
r.encoding = 'utf-8'

file_path = file_path_crib.format(category=category_dict['name'], year=now.year, month=now.month,day=now.day)

m_path = BASE_FILE_DIR / file_path
m_path.parent.mkdir(parents=True, exist_ok=True)

## Save file
with open(m_path, 'w') as f_out:
    f_out.write(r.text)

Transform

In [17]:
df = pd.read_csv(m_path,encoding='latin-1')
df.head(5)

,Cod_Loc,IdProvincia,IdDepartamento,Observaciones,Categoría,Provincia,Departamento,Localidad,Nombre,Dirección,...,Información adicional,Latitud,Longitud,TipoLatitudLongitud,Fuente,tipo_gestion,Pantallas,Butacas,espacio_INCAA,año_actualizacion
0,10049030,10,10049,NaN,Salas de cine,Catamarca,Capital,Catamarca,Cinemacenter,Intendente Mamerto Medina 220,...,NaN,-28.464737,-65.800675,Localización precisa,INCAA / SInCA,Privado comercial,5,743,NaN,2018
1,10091150,10,10091,NaN,Salas de cine,Catamarca,Santa Maria,Santa María,Centro Cultural San Agustín,San Martin 173,...,NaN,-26.693859,-66.049058,Localización precisa,INCAA / SInCA,Privado comercial,1,440,0,2018
2,22140060,22,22140,NaN,Salas de cine,Chaco,San Fernando,Resistencia,Los Cines De La Costa,Av. Sarmiento 2600,...,NaN,-27.430995,-58.962672,Localización precisa,INCAA / SInCA,Privado comercial,5,820,NaN,2018
3,26091020,26,26091,NaN,Salas de cine,Chubut,Sarmiento,Sarmiento,Deborah Jones De Williams,Reg. Inf. Mec. 25 Esquina 20 De Junio,...,NaN,-45.594374,-69.069594,Localización precisa,INCAA / SInCA,Público municipal,1,80,NaN,2018
4,18007010,18,18007,NaN,Salas de cine,Corrientes,Bella Vista,Bella Vista,Fantasio,Salta 1059,...,NaN,-28.508494,-59.045464,Localización precisa,INCAA / SInCA,Privado comercial,1,240,NaN,2018

In [18]:
df.groupby('Provincia', as_index=False).count()[['Provincia','Pantallas', 'Butacas', 'espacio_INCAA']]

                          Provincia  Pantallas  Butacas  espacio_INCAA
0                      Buenos Aires        106      106             20
1                         Catamarca          4        4              2
2                             Chaco          4        4              1
3                            Chubut          9        9              4
4   Ciudad Autónoma de Buenos Aires         35       35              3
5                        Corrientes          8        8              1
6                           Córdoba         35       35              2
7                        Entre Ríos         13       13              2
8                           Formosa          2        2              1
9                             Jujuy          4        4              2
10                         La Pampa          6        6              2
11                         La Rioja          5        5              1
12                          Mendoza         16       16              2
13                         Misiones          6        6              2
14                          Neuquén          5        5              3
15                        Río Negro          7        7              4
16                            Salta         10       10              2
17                         San Juan          6        6              2
18                         San Luis          4        4              0
19                       Santa Cruz          5        5              2
20                         Santa Fe         23       23              3
21              Santiago del Estero          5        5              1
22                 Tierra del Fuego          3        3              0
23                          Tucumán          8        8              2

In [19]:
df.dtypes

Cod_Loc                    int64
IdProvincia                int64
IdDepartamento             int64
Observaciones            float64
Categoría                 object
Provincia                 object
Departamento              object
Localidad                 object
Nombre                    object
Dirección                 object
Piso                      object
CP                         int64
cod_area                  object
Teléfono                  object
Mail                      object
Web                       object
Información adicional    float64
Latitud                  float64
Longitud                 float64
TipoLatitudLongitud       object
Fuente                    object
tipo_gestion              object
Pantallas                  int64
Butacas                    int64
espacio_INCAA             object
año_actualizacion          int64
dtype: object

In [20]:
renamed_cols = {
    'Cod_Loc': 'cod_localidad',
    'IdProvincia': 'id_provincia',
    'IdDepartamento': 'id_departamento',
    'Provincia': 'provincia',
    'Categoría': 'categoria',
    'Dirección': 'domicilio',
    'CP': 'codigo postal',
    'Localidad': 'localidad',
    'Nombre': 'nombre',
    'Domicilio': 'domicilio',
    'Teléfono': 'número de teléfono',
    'Mail': 'mail',
    'Web': 'web',
    
}

df = df.rename(columns = renamed_cols)

colum_list = [
    'cod_localidad',
    'id_provincia',
    'id_departamento',
    'categoria',
    'provincia',
    'localidad',
    'nombre',
    'domicilio',
    'codigo postal',
    'número de teléfono',
    'mail',
    'web',
]

df_cine= df[colum_list]

Bibliotecas

In [21]:
now = datetime.now()

category_dict = categories[2]
r = requests.get(category_dict['url'])
r.encoding = 'utf-8'

file_path = file_path_crib.format(category=category_dict['name'], year=now.year, month=now.month,day=now.day)

m_path = BASE_FILE_DIR / file_path
m_path.parent.mkdir(parents=True, exist_ok=True)

## Save file
print(categories[2]['name'])
with open(m_path, 'w') as f_out:
    f_out.write(r.text)

bibliotecas_populares

Transform

In [24]:
df = pd.read_csv(m_path,encoding='latin-1')

In [25]:
renamed_cols = {
    'Cod_Loc': 'cod_localidad',
    'IdProvincia': 'id_provincia',
    'IdDepartamento': 'id_departamento',
    'Provincia': 'provincia',
    'Categoría': 'categoria',
    'Dirección': 'domicilio',
    'CP': 'codigo postal',
    'Localidad': 'localidad',
    'Nombre': 'nombre',
    'Domicilio': 'domicilio',
    'Teléfono': 'número de teléfono',
    'Mail': 'mail',
    'Web': 'web',
    
}

df = df.rename(columns = renamed_cols)

colum_list = [
    'cod_localidad',
    'id_provincia',
    'id_departamento',
    'categoria',
    'provincia',
    'localidad',
    'nombre',
    'domicilio',
    'codigo postal',
    'número de teléfono',
    'mail',
    'web',
]
df_biblio= df[colum_list]

In [26]:
df_biblio['id_departamento'].isna().unique()

array([False])

In [27]:
dfs = {'asd': df_m,'fda': df_cine,'gfd': df_biblio}

In [28]:
dfss = pd.concat(dfs, axis=0)

In [29]:
dfss.dtypes

cod_localidad          int64
id_provincia           int64
id_departamento        int64
categoria             object
provincia             object
localidad             object
nombre                object
domicilio             object
codigo postal         object
número de teléfono    object
mail                  object
web                   object
dtype: object

In [30]:
dfss.groupby('categoria', as_index=False).size()

                            categoria  size
0               Bibliotecas Populares  2017
1  Espacios de Exhibición Patrimonial  1182
2                       Salas de cine   329

In [31]:
dfss.groupby(['categoria', 'provincia'], as_index=False).size()

                categoria                        provincia  size
0   Bibliotecas Populares                     Buenos Aires   543
1   Bibliotecas Populares                        Catamarca    38
2   Bibliotecas Populares                            Chaco    70
3   Bibliotecas Populares                           Chubut    48
4   Bibliotecas Populares  Ciudad Autónoma de Buenos Aires    43
..                    ...                              ...   ...
68          Salas de cine                       Santa Cruz     5
69          Salas de cine                         Santa Fe    23
70          Salas de cine              Santiago del Estero     5
71          Salas de cine                 Tierra del Fuego     3
72          Salas de cine                          Tucumán     8

[73 rows x 3 columns]

In [32]:
lst = list()
for name, df in dfs.items():
    lst.append({'source': name, 'count': df.size,})
    
pd.DataFrame(lst)

  source  count
0    asd  14184
1    fda   3948
2    gfd  24204